require("sudohaxe.remap")
require("sudohaxe.set")

print("Welcome to @sudohaxe's Nvim!")
print("================================================")
print("Enabled:")
print("================================================")
print("vim-surround")
print("harpoon(view harpoon: <C-e>, mark: <leader>a )")
print("git(<leader>gs)")
print("fugitive[undo](<leader>u)")
print("================================================")
print("Keymaps:")
print("================================================")
print("project view(:Exp): <leader>pv")
print("project search(Grep): <leader>ps")
print("project find(Fuzzy file find): <leader>pf")
