require("sudohaxe.remap")
require("sudohaxe.set")

print("Welcome to @sudohaxe's Nvim!")
print("================================================")
print("Enabled:")
print("================================================")
print("vim-surround")
print("harpoon(view harpoon: <C-e>, mark: <leader>a )")
print("git(<leader>gs)")
print("fugitive[undo](<leader>u)")
print("================================================")
print("Keymaps:")
print("================================================")
print("project view(Telescope): <leader>pv")
print("project search(Grep): <leader>ps")
print("project find(Fuzzy file find): <leader>pf")
print("================================================")
print("Lsp commands:")
print("================================================")
print("Go to definition: gd")
print("Code action: <leader>vca")
print("References: <leader>vrr")
print("Rename: <leader>vrn")
print("Signature help: <C-h>")
